// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiVz7dJaik98aT4n7rz2NAtT-87bpYkRI',
    appId: '1:387136791522:web:4c19a565bc5a42d8d70fbb',
    messagingSenderId: '387136791522',
    projectId: 'ecos-753d2',
    authDomain: 'ecos-753d2.firebaseapp.com',
    storageBucket: 'ecos-753d2.firebasestorage.app',
    measurementId: 'G-17Y4ZWR7WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5wuvP54N5f_g1JxcPQw8SRoVE7t4j94',
    appId: '1:387136791522:android:3cdd096cb9360a3fd70fbb',
    messagingSenderId: '387136791522',
    projectId: 'ecos-753d2',
    storageBucket: 'ecos-753d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxx8g3pCr4lUmQ_mybh3CVGcz7W2_MOxQ',
    appId: '1:387136791522:ios:a39fb834d0fd6ee1d70fbb',
    messagingSenderId: '387136791522',
    projectId: 'ecos-753d2',
    storageBucket: 'ecos-753d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxx8g3pCr4lUmQ_mybh3CVGcz7W2_MOxQ',
    appId: '1:387136791522:ios:a39fb834d0fd6ee1d70fbb',
    messagingSenderId: '387136791522',
    projectId: 'ecos-753d2',
    storageBucket: 'ecos-753d2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
